# Generated by Django 6.0 on 2026-08-10 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_remove_delivery_delivery_date_delivery_created_at_and_more'),
        ('sales', '0004_alter_invoice_invoice_number'),
        ('shop', '0002_clientorder_updated_at_clientorder_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='shop.clientorder'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='sales.invoice'),
        ),
    ]
