# Generated by Django 6.0 on 2026-08-25 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_delivery_order_alter_delivery_invoice'),
        ('sales', '0006_invoice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='order',
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='sales.invoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('assigned', 'Assignée'), ('in_progress', 'En cours'), ('delivered', 'Livrée'), ('failed', 'Échouée')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('speed', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='deliveries.delivery')),
            ],
        ),
    ]
